name: Generate and Deploy JSDoc

on:
  push:
    branches:
      - main

jobs:
  jsdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install JSDoc and dependencies
        run: |
          npm install jsdoc -g
          npm install minami
          npm install taffydb

      - name: Generate JSDoc
        run: |
          jsdoc -d doc src/peerjs-groups.js -t ./node_modules/minami

      - name: Debug List files in doc directory AFTER jsdoc
        run: |
          ls -la doc/

      - name: Commit and Push Documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs(jsdoc): Update JSDoc documentation'
          repository: .
          branch: ${{ github.head_ref || github.ref_name }}
          commit_user_name: MaxAI-FreeAI
          commit_user_email: freeai@maxai.com

      - name: Debug Check Git config
        run: |
          git config --list

