name: Publish to npm on Tag

on:
  push:
    tags:
      - 'v*'  # Trigger on tags matching v* (e.g., v1.2.3)

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for reading package.json
      packages: write # Required to publish to npm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Authenticate with npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        working-directory: ${{ github.workspace }}/dist
        run: npm publish --access public
